name: "conda-version-bumper"
author: "John Muchovej"
description: "Bumps the package based on the latest-published Conda version."
inputs:
  owner:
    description: "Repository owner to source packages from."
    required: false
    default: "conda-forge"
  package:
    description: "Package name."
    required: true
outputs:
  conda_version:
    description: "Latest Conda version found."
  conda_build_n:
    description: "Latest Conda version's build number."
  pkg_version:
    description: "Latest desired package version."
  pkg_build_n:
    description: "Latest desired package build number."
runs:
  using: "node16"
  main: "dist/index.js"
