name: "Build Dockerfile for Mamba-based Environment"

on:
  workflow_call:
    inputs:
      docker_tag:
        required: true
        type: string
      build_context:
        required: true
        type: string

jobs:
  build-environment:
    runs-on: "ubuntu-latest"
    steps:
      - id: "setup"
        run: |
          echo "build-date=$(date)" >> $GITHUB_OUTPUT

      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@v3"

      - id: "setup-qemu"
        name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "linux/amd64,linux/arm64"

      - id: "setup-buildx"
        name: "Setup Buildx"
        uses: "docker/setup-buildx-action@v2"
        with:
          install: true

      - id: "login-dockerhub"
        name: "Login to DockerHub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN    }}"

      - id: "login-ghcr"
        name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN    }}"

      - id: "build"
        name: "Build and push Docker images"
        uses: "docker/build-push-action@v3"
        with:
          push: true
          platforms: "linux/amd64,linux/arm64"
          context: "${{ inputs.build_context }}"
          build-args: |
            BUILD_DATE=${{ steps.setup.outputs.build-date }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/baseimage:${{ inputs.docker_tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/baseimage:${{ inputs.docker_tag }}-${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/baseimage:${{ inputs.docker_tag }}
            ghcr.io/${{ github.repository_owner }}/baseimage:${{ inputs.docker_tag }}-${{ github.sha }}
