name: "Build Dockerfile for Mamba-based Environment"

on:
  workflow_call:
    inputs:
      package_owner:
        required: true
        type: string
      package_name:
        required: true
        type: string
      build_context:
        required: true
        type: string
      image_name:
        required: true
        type: string

jobs:
  build-environment:
    runs-on: "ubuntu-latest"
    steps:
      - id: "setup"
        run: "echo '::set-output name=build-date::$(date)'"

      - id: "checkout"
        name: "Checkout repository"
        uses: "actions/checkout@v3"

      - id: "vbump"
        name: "Version Bump"
        uses: "./.github/actions/version-bumper"
        with:
          owner: "${{ inputs.package_owner  }}"
          package: "${{ inputs.package_name }}"

      - id: "setup-qemu"
        name: "Setup QEMU"
        uses: "docker/setup-qemu-action@v2"
        with:
          platforms: "linux/amd64,linux/arm64"

      - id: "setup-buildx"
        name: "Setup Buildx"
        uses: "docker/setup-buildx-action@v2"
        with:
          install: true

      - id: "login-dockerhub"
        name: "Login to DockerHub"
        uses: "docker/login-action@v2"
        with:
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
          password: "${{ secrets.DOCKERHUB_TOKEN    }}"

      - id: "login-ghcr"
        name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.repository_owner }}"
          password: "${{ secrets.GITHUB_TOKEN    }}"

      - id: "build"
        name: "Build and push Docker images"
        uses: "docker/build-push-action@v3"
        with:
          push: true
          platforms: "linux/amd64,linux/arm64"
          context: "${{ inputs.build_context }}"
          build-args: |
            CONDA_VERSION=${{ steps.vbump.outputs.conda_version }}
            CONDA_BUILD_N=${{ steps.vbump.outputs.conda_build }}
            VERSION=${{ steps.vbump.outputs.pkg_version }}
            BUILD_N=${{ steps.vbump.outputs.pkg_build_n }}
            BUILD_DATE=${{ steps.setup.outputs.build-date }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.image_name }}:${{ steps.vbump.outputs.pkg_version }}
            ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ steps.vbump.outputs.pkg_version }}
